Add a check when topUpReward is 0
ElrondNetwork/starter-dapp pull request #40
Opened 2021-02-25 23:28 UTC by mihaieremia

2021-02-25 23:37 UTC, alexandru-g commented on react-delegationdashboard/src/components/Layout/APRCalculation.ts
> +  let validatorTopUpReward = validatorTopUpStake / networkTopUpStake;
The issue observed was that `networkTopUpStake` was 0, so division by 0 produced a NaN. If `topUpReward` was 0 then apr should have been displayed as 0.
I would suggest something like this:
`const validatorTopUpReward = networkTopUpStake > 0 ? (validatorTopUpStake / networkTopUpStake) * topUpReward : 0;`

However, the cause of the problem seems to have been that `networkTotalStake` was equal to `networkBaseStake`, which I find quite impossible... I think it needs to be investigated where those values are produced (in the dapp) @LucianMincu .

2021-02-26 13:44 UTC, radumojic submitted a review, later dismissed

2021-03-01 08:51 UTC, danielailie requested changes

2021-03-01 08:51 UTC, danielailie commented on react-delegationdashboard/src/components/Layout/APRCalculation.ts
>    const validatorTotalStake = parseInt(denominateValue(totalActiveStake));
For validatorTopUpReward we should use the validatorTopUpStake not the validatorTotalStake

2021-03-01 11:06 UTC, danielailie approved these changes

2021-03-01 14:08 UTC, radumojic approved these changes

2021-03-01 14:14 UTC, merged