Fix admin max delegation cap card
ElrondNetwork/starter-dapp pull request #42
Opened 2021-02-26 00:07 UTC by mihaieremia

The max delegation cap card had a bug for the owner dashboard when the delegation cap was infinity the card was not displayed.
I added a new check for '' as the card was displayed for few seconds and disappeared after when the value is infinity which is creating a UI glitch.

2021-02-26 16:30 UTC, danielailie approved these changes

2021-03-01 12:09 UTC, danielailie requested changes

2021-03-01 12:09 UTC, danielailie commented on react-delegationdashboard/src/config.testnet.ts
>    explorerAddress: 'http://testnet-explorer.elrond.com/',
can you undo this config change?

2021-03-01 16:17 UTC, danielailie approved these changes

2021-03-01 16:19 UTC, radumojic approved these changes

2021-03-01 16:20 UTC, merged