Devnet configs
ElrondNetwork/starter-dapp pull request #65
Opened 2021-03-12 12:23 UTC by iulianpascalau

- added devnet configs
- changed README.md

2021-03-15 08:37 UTC, danielailie requested changes

2021-03-15 08:37 UTC, danielailie commented on react-delegationdashboard/README.md
If you can change this step in build solution or something similar

2021-03-15 08:37 UTC, danielailie commented on react-delegationdashboard/README.md
And maybe here add a comment with build for production

2021-03-16 09:38 UTC, danielailie approved these changes

2021-03-16 09:39 UTC, radumojic approved these changes

2021-03-16 09:39 UTC, merged